name: ganimation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.16.3
  - opencv=4.1.0
  - openssl=1.1.1c
  - pillow=6.0.0
  - pip=19.1
  - python=3.6.8
  - pytorch=1.1.0
  - scipy=1.3.0
  - tensorboard=1.13.1
  - tensorboardx=1.7
  - tensorflow=1.13.1
  - torchvision=0.3.0

